# Generated by Django 3.1.3 on 2020-11-21 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAFF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('creator', models.CharField(help_text='Enter the name of the creator', max_length=200)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(help_text='Enter a caption', max_length=200)),
                ('content', models.BinaryField()),
                ('thumbnail', models.BinaryField()),
            ],
            options={
                'ordering': ['upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a caption', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a caption', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Enter your comment', max_length=1000)),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webshop.caff')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='caff',
            name='captions',
            field=models.ManyToManyField(help_text='Captions for the CAFF', to='webshop.Caption'),
        ),
        migrations.AddField(
            model_name='caff',
            name='tags',
            field=models.ManyToManyField(help_text='Tags for the CAFF', to='webshop.Tag'),
        ),
        migrations.AddField(
            model_name='caff',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
